# Generated by Django 5.1.4 on 2024-12-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='date',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='time',
            field=models.CharField(default=-10, max_length=8),
            preserve_default=False,
        ),
    ]
