# Generated by Django 5.1.4 on 2025-02-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core_Application', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
